import Head from "next/head";

const BaseLayout = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>Chain with</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      {children}
    </>
  );
};

export default BaseLayout;
